"""Generate a proxy DLL: forwarding thunks + module definition file.

The mod ships as winmm.dll in the game folder. isaac-ng.exe imports winmm statically,
so Windows loads us before main() runs, which is exactly when we want to patch.

Everything the real DLL provides has to keep working: for winmm, OpenAL32.dll pulls 17
functions from it and EOSSDK 5. Rather than shipping a renamed copy of the Microsoft binary, each
export becomes a naked `jmp [slot]` thunk that binds lazily against the real
%SystemRoot%\\System32\\winmm.dll (WoW64 redirects this to SysWOW64 for our 32-bit build).
A naked jmp preserves the stack frame, so it is signature-agnostic: it works for every
calling convention and argument count without us knowing any of them.

The module name is taken from the file you point it at, so the same generator produces
the winmm proxy we ship by default and any alternative name. That matters because a
handful of people report the loader never picking us up at all, and a different import
of the same executable is the cheapest thing left to try.

Usage:  python tools/gen_proxy.py [path to the real DLL]
Writes: src/<name>_thunks.cpp, src/<name>.def
"""
import os
import struct
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.normpath(os.path.join(HERE, "..", "src"))


def read_exports(path):
    """-> [(name_or_None, ordinal)] for every export of a PE image."""
    d = open(path, "rb").read()
    pe = struct.unpack_from("<I", d, 0x3C)[0]
    if d[pe:pe + 4] != b"PE\0\0":
        raise ValueError("not a PE: %s" % path)
    coff = pe + 4
    nsec = struct.unpack_from("<H", d, coff + 2)[0]
    optsz = struct.unpack_from("<H", d, coff + 16)[0]
    opt = coff + 20
    magic = struct.unpack_from("<H", d, opt)[0]
    dd = opt + (96 if magic == 0x10B else 112)
    exp_rva, _ = struct.unpack_from("<II", d, dd)

    secs = []
    so = opt + optsz
    for i in range(nsec):
        o = so + i * 40
        vs = struct.unpack_from("<I", d, o + 8)[0]
        va = struct.unpack_from("<I", d, o + 12)[0]
        rs = struct.unpack_from("<I", d, o + 16)[0]
        rp = struct.unpack_from("<I", d, o + 20)[0]
        secs.append((va, max(vs, rs), rp))

    def r2o(rva):
        for va, sz, rp in secs:
            if va <= rva < va + sz:
                return rp + (rva - va)
        raise ValueError("rva %#x outside every section" % rva)

    e = r2o(exp_rva)
    ord_base = struct.unpack_from("<I", d, e + 16)[0]
    n_funcs, n_names = struct.unpack_from("<II", d, e + 20)
    names_rva, ords_rva = struct.unpack_from("<II", d, e + 32)

    by_ordinal = {}
    if n_names:
        no = r2o(names_rva)
        oo = r2o(ords_rva)
        for i in range(n_names):
            nr = struct.unpack_from("<I", d, no + 4 * i)[0]
            off = r2o(nr)
            nm = d[off:d.index(b"\0", off)].decode("ascii")
            idx = struct.unpack_from("<H", d, oo + 2 * i)[0]
            by_ordinal[ord_base + idx] = nm

    out = []
    for i in range(n_funcs):
        out.append((by_ordinal.get(ord_base + i), ord_base + i))
    return out


def main():
    real = sys.argv[1] if len(sys.argv) > 1 else r"C:\Windows\SysWOW64\winmm.dll"
    base = os.path.splitext(os.path.basename(real))[0].lower()
    exports = read_exports(real)
    named = [(n, o) for n, o in exports if n]
    print("%s: %d exports, %d named" % (real, len(exports), len(named)))

    cpp = [
        "// GENERATED by tools/gen_proxy.py -- do not edit.",
        "// Forwarding thunks for every %s export, bound lazily against the real DLL." % base,
        "#include <windows.h>",
        "",
        "extern \"C\" void* g_slot[%d] = {};" % len(named),
        "static const char* const kNames[%d] = {" % len(named),
    ]
    cpp += ["    \"%s\"," % n for n, _o in named]
    cpp += [
        "};",
        "",
        "// Bound on first call rather than in DllMain: calling LoadLibrary under the",
        "// loader lock is a documented way to deadlock.",
        "extern \"C\" void* __cdecl ProxyBind(int i) {",
        "    static HMODULE real = nullptr;",
        "    if (!real) {",
        "        char p[MAX_PATH];",
        "        UINT n = GetSystemDirectoryA(p, MAX_PATH);",
        "        if (!n || n >= MAX_PATH - 12) return nullptr;",
        "        lstrcatA(p, \"\\\\%s.dll\");" % base,
        "        real = LoadLibraryA(p);",
        "        if (!real) return nullptr;",
        "    }",
        "    void* fn = (void*)GetProcAddress(real, kNames[i]);",
        "    g_slot[i] = fn;",
        "    return fn;",
        "}",
        "",
    ]

    # A naked `jmp` leaves the caller's frame untouched, so one thunk shape serves
    # every signature and calling convention winmm exposes.
    for i, (name, _ordinal) in enumerate(named):
        cpp += [
            "extern \"C\" __declspec(naked) void proxy_%s() {" % name,
            "    __asm {",
            "        mov  eax, dword ptr [g_slot + %d]" % (i * 4),
            "        test eax, eax",
            "        jnz  short have_it",
            "        push %d" % i,
            "        call ProxyBind",
            "        add  esp, 4",
            "    have_it:",
            "        jmp  eax",
            "    }",
            "}",
        ]

    with open(os.path.join(SRC, base + "_thunks.cpp"), "w", encoding="ascii") as f:
        f.write("\n".join(cpp) + "\n")

    d = ["LIBRARY " + base, "EXPORTS"]
    for name, ordinal in named:
        d.append("    %s = proxy_%s @%d" % (name, name, ordinal))
    with open(os.path.join(SRC, base + ".def"), "w", encoding="ascii") as f:
        f.write("\n".join(d) + "\n")

    print("wrote src/%s_thunks.cpp and src/%s.def (%d thunks)" % (base, base, len(named)))


if __name__ == "__main__":
    main()
